#ifndef PICTURE_PREPROCESSOR_RESOURCE_H
#define PICTURE_PREPROCESSOR_RESOURCE_H

#define IDC_STATIC -1

#define IDC_MAIN_EDIT 51
#define IDC_MAIN_STATUSBAR 52
#define IDC_MAIN_TOOLBAR 53

#define IDI_MYEXEICON 201
#define IDI_MYICON 202

#define IDD_SELECTDIRECTORY 300
#define IDC_SELECTINPUTDIRECTORY 301
#define IDC_INPUTDIRECTORY 302
#define IDC_SELECTOUTPUTDIRECTORY 303
#define IDC_OUTPUTDIRECTORY 304
#define IDC_STARTBUTTON 305

#define IDD_PROCESSPROGRESS 310
#define IDC_PROGRESSBAR 311

#define ID_TIMER_PROGRESSBAR 400

#endif
